### ISSUE TITLE
arm build meta-issue

### ISSUE THREAD

**Issue by adrienkohlbecker** [DataDog/datadog-agent#2499]
Hi! 👋 

I've been working on https://github.com/adrienkohlbecker/datadog-agent-arm in my free time, to try to get me an agent properly compiled for arm platforms, to use it on my Raspberry Pis.

I understand this is not yet supported in any official capacity by Datadog, but since this is OSS, I thought I would upstream a number of fixes. 

# Pull requests

Here is the current list of PRs:

- [x] https://github.com/DataDog/datadog-process-agent/pull/198
- [x] https://github.com/DataDog/omnibus-software/pull/218
- [x] https://github.com/DataDog/omnibus-software/pull/216
- [x] https://github.com/DataDog/omnibus-software/pull/314
- [x] https://github.com/DataDog/datadog-agent/pull/2461
- [ ] https://github.com/DataDog/datadog-agent/pull/2495 
- [x] https://github.com/DataDog/datadog-agent/pull/2497
- [x] https://github.com/DataDog/datadog-agent/pull/3456

# Other known issues

- (`armv7`/`armhf`) The trace agent makes heavy use of atomic.*Int64 class of functions, which all panic on 32 bits architectures. I was able to fix the process agent here https://github.com/DataDog/datadog-process-agent/pull/198 but for trace I think somebody from Datadog would be better equipped to make the right choices, given the amount of call sites.
- The `aerospike` and `ibm_mq` don't build on ARM and are thus blacklisted.

# Results

I was able to package a full working agent for arm using the script in the repo I mentionned above.

Agent starts and runs checks properly:

```
Oct 19 19:23:01 tender-wozniak systemd[1]: Started "Datadog Agent".
Oct 19 19:23:01 tender-wozniak agent[5622]: 2018-10-19 19:23:01 UTC | INFO | (log.go:441 in func1) | config.Load()
Oct 19 19:23:01 tender-wozniak agent[5622]: 2018-10-19 19:23:01 UTC | INFO | (log.go:441 in func1) | config.load succeeded
Oct 19 19:23:01 tender-wozniak agent[5622]: 2018-10-19 19:23:01 UTC | INFO | (start.go:135 in StartAgent) | Starting Datadog Agent v6.6.0-rc.1+git.1.02d20d3
Oct 19 19:23:01 tender-wozniak agent[5622]: 2018-10-19 19:23:01 UTC | INFO | (start.go:146 in StartAgent) | pid '5622' written to pid file '/opt/datadog-agent/run/agent.pid'
Oct 19 19:23:02 tender-wozniak agent[5622]: 2018-10-19 19:23:02 UTC | INFO | (start.go:153 in StartAgent) | Hostname is: tender-wozniak
Oct 19 19:23:02 tender-wozniak agent[5622]: 2018-10-19 19:23:02 UTC | INFO | (security.go:132 in FetchAuthToken) | Saved a new authentication token to /etc/datadog-agent/auth_token
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (start.go:172 in StartAgent) | GUI server port -1 specified: not starting the GUI.
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (config.go:583 in getMultipleEndpoints) | No API key provided for domain "https://app.datadoghq.com", removing
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (forwarder.go:154 in Start) | Forwarder started, sending to 0 endpoint(s) with 1 worker(s) each:
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | ERROR | (forwarder_health.go:90 in healthCheckLoop) | No valid api key found, reporting the forwarder as unhealthy.
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (udp.go:74 in Listen) | dogstatsd-udp: starting to listen on 127.0.0.1:8125
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | WARN | (launcher.go:46 in NewLauncher) | Could not setup the docker launcher: Cannot connect to the Docker daemon at
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (logs.go:50 in Start) | Starting logs-agent...
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | ERROR | (auditor.go:159 in recoverRegistry) | open /opt/datadog-agent/run/registry.json: no such file or directory
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (logs.go:53 in Start) | logs-agent started
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (tagger.go:79 in Init) | starting the tagging system
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (runner.go:94 in NewRunner) | Runner started with 4 workers.
Oct 19 19:23:13 tender-wozniak agent[5622]: 2018-10-19 19:23:13 UTC | INFO | (collector.go:55 in NewCollector) | Embedding Python 2.7.9 (default, Oct 18 2018, 13:38:43) [GCC 5.4.0 2016060
Oct 19 19:23:17 tender-wozniak agent[5622]: 2018-10-19 19:23:17 UTC | INFO | (file.go:70 in Collect) | File: searching for configuration files at: /etc/datadog-agent/conf.d
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (file.go:70 in Collect) | File: searching for configuration files at: /opt/datadog-agent/bin/agent/dist/conf.d
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (file.go:74 in Collect) | Skipping, open /opt/datadog-agent/bin/agent/dist/conf.d: no such file or directory
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (file.go:70 in Collect) | File: searching for configuration files at:
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (file.go:74 in Collect) | Skipping, open : no such file or directory
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (check.go:261 in Configure) | could not get a check instance with the new api: __init__() takes at least 4 arg
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (check.go:262 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the con
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (check.go:287 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_conf
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (check.go:261 in Configure) | could not get a check instance with the new api: __init__() takes at least 4 arg
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (check.go:262 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the con
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | WARN | (check.go:287 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_conf
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check cpu
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check cpu with an interval of 15s
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check disk
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check disk with an interval of 15s
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check file_handle
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check file_handle with an interval of 15s
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check io
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check io with an interval of 15s
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check load
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check load with an interval of 15s
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check memory
Oct 19 19:23:18 tender-wozniak agent[5622]: 2018-10-19 19:23:18 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check memory with an interval of 15s
```

Ran the python hello world from the doc to confirm the runtime is embedded correctly

```
root@tender-wozniak:/opt/agent/go/src/github.com/DataDog/datadog-agent# sudo -u dd-agent datadog-agent check hello
=== Series ===
{
  "series": [
    {
      "metric": "hello.world",
      "points": [
        [
          1539977096,
          1
        ]
      ],
      "tags": null,
      "host": "tender-wozniak",
      "type": "gauge",
      "interval": 0,
      "source_type_name": "System"
    }
  ]
}
=========
Collector
=========

  Running Checks
  ==============

    hello (unversioned)
    -------------------
        Instance ID: hello:d884b5186b651429 [OK]
        Total Runs: 1
        Metric Samples: 1, Total: 1
        Events: 0, Total: 0
        Service Checks: 0, Total: 0
        Average Execution Time : 0s
```

**Comment by achntrl** [comment]
I've managed to build the Agent 6.9.0 on armv7. I had to exclude the trace-agent and the process agent (hopefully the trace agent will work oob at 6.10 after the merge in `datadog-agent`)
https://github.com/DataDog/datadog-agent/commits/achntrl/armv7

I built a docker image: https://hub.docker.com/r/achntrl/datadog-agent/tags that only run the `datadog-agent`. Please note that I built it on my personal time as a hobby because I run some raspberry pis at home. **This is not officially maintained by Datadog** 


I had to modify release.json to build on my branches for `integration-core` (IBM MQ breaks the build on arm) https://github.com/DataDog/integrations-core/commits/achntrl/armv7 and `omnibus-software` (to add libffi to the build of datadog-pip) https://github.com/DataDog/omnibus-software/tree/achntrl/armv7

```diff
diff --git a/release.json b/release.json
index 7efa2da..c460771 100644
--- a/release.json
+++ b/release.json
@@ -9,10 +9,10 @@
                "JMXFETCH_HASH": "244cdcec15efb9fc9923a868787d3e6a2dad95e169dbee4cb7fe6d122d5109cf"
        },
        "6.9.0": {
-               "INTEGRATIONS_CORE_VERSION": "6.9.0",
+               "INTEGRATIONS_CORE_VERSION": "achntrl/armv7",
                "TRACE_AGENT_VERSION": "6.9.0",
                "PROCESS_AGENT_VERSION": "6.9.0",
-               "OMNIBUS_SOFTWARE_VERSION": "6.9.0",
+               "OMNIBUS_SOFTWARE_VERSION": "achntrl/armv7",
                "OMNIBUS_RUBY_VERSION": "datadog-5.5.0",
                "JMXFETCH_VERSION": "0.24.1",
                "JMXFETCH_HASH": "244cdcec15efb9fc9923a868787d3e6a2dad95e169dbee4cb7fe6d122d5109cf"
```

I briefly tried to build the process-agent from source but ran into some (probably unrelated issues) with rake and apt so I didn't push further (maybe I will with a new VM at 6.10). I don't know how portable is the eBPF thing

@gzussa, I saw that you assigned yourself on the issue. Let me know if you want to discuss this a bit more to see if there are thing that we can push in the main repo.

**Comment by gzussa** [comment]
@achntrl I assigned myself because I wanted to use it on my own PI 😄

**Comment by adrienkohlbecker** [comment]
Closing as I'm now able to build on arm without issue https://github.com/adrienkohlbecker/datadog-agent-arm/pull/4
